= Compare and contrast networking appliances, applications, and functions.
* Physical and virtual appliances

=== *Router*
* *Function:* Connects two or more packet-switched networks
* Routers examine incoming IP address and its network portion of the addres. It will guide the packet to its destination.
** If destination is not on the same network as the router, the router will find the best route for that data
** If destination is on the same network as the router, it will use the host portion of the IP to send data to the correct device on the network
* Use routing tables to keep track of the locations of devices on the network
* *Benefits*
* *Types*
** Core Routers
** Edge Routers
** Distribution Routers
** Wireless Routers
** Virtual Routers


=== *Switch*
* *Function:* Allows two or more devices to connect and send data packets back and forth
Layer 2 Switch:: Uses the physical Address (MAC) to locate other devices. When first connected to the switch, devices send their MAC adresses to the switch
Layer 3 Switch:: Uses IP addresses to forward Packets, faster and has a higher port density to switch and route data
Layer 3 Address Resolution Protocal (ARP):: Hardware based arp which takes the IP address (the logical address) and convert it to a physical address (MAC)



=== *Firewall*
* *Function:* 

=== *Intrusion detection system (IDS) / Intrusion prevention system (IPS)*
* *Function:* 

=== *Load balancer*
* *Function:* distributes the Network load by directing massive flows of network traffic or requests among multiple servers or machines. 
** This provides higher availablitly and reliablity if one server were to fail. All traffic can be redirected from the failed server to the one that is still operating. 
** Allows scalability as servers can be provisioned or deprovisioned in the background

=== *Proxy*
* *Function:* 

=== *Network-attached storage (NAS)*
* *Function:* 

=== *Storage area network (SAN)*
* *Function:* 

=== *Wireless*
* *Function:* 

=== *Access point (AP)*
* *Function:* 

=== *Controllers*
* *Function:* 

=== *Applications*
* *Function:* 

=== *Content delivery network (CDN)*
* *Function:* 

=== *Functions*
* *Function:* 

=== *Virtual private network (VPN)*
* *Function:* 

=== *Quality of service (QoS)*
* *Function:* 

=== *Time to live (TTL)*
* *Function:* 
